apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.ingress.name}}
  namespace: {{.Values.k8Namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /gwas/depo-curation/$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host:
      http:
        paths:
          - path: /gwas/depo-curation(/|$)(.*)
            backend:
              serviceName: gwas-curation-ui
              servicePort: 80
